"use client";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
export const metadata = {
  title: "press-agency",
  description: "Generated by team loading",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[##f7f7f7] text-black">
        <Navbar />
        <div className="min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
